apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpt09-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dpt09
  template:
    metadata:
      labels:
        app: dpt09
    spec:
      containers:
      - name: dpt09
        image: dpt09-local:latest   # local image
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dpt09-service
spec:
  selector:
    app: dpt09
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
