apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpt09-deployment
  namespace: dev
  labels:
    app: dpt09
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dpt09
  template:
    metadata:
      labels:
        app: dpt09
    spec:
      containers:
        - name: dpt09
          image: charan208/dpt09:v12
          ports:
            - containerPort: 3000
